import { Events } from "discord.js"

export const botEvents = [
  Events.ClientReady,
  Events.ChannelCreate,
  Events.ChannelDelete,
  Events.ChannelUpdate,
  Events.ChannelPinsUpdate,
  Events.GuildCreate,
  Events.GuildDelete,
  Events.GuildUpdate,
  Events.GuildBanAdd,
  Events.GuildBanRemove,
  Events.GuildMemberAdd,
  Events.GuildMemberRemove,
  Events.GuildMemberUpdate,
  Events.GuildRoleCreate,
  Events.GuildRoleDelete,
  Events.GuildRoleUpdate,
  Events.MessageCreate,
  Events.MessageDelete,
  Events.MessageUpdate,
  Events.MessageReactionAdd,
  Events.MessageReactionRemove,
  Events.MessageReactionRemoveAll,
  Events.PresenceUpdate,
  Events.TypingStart,
  Events.UserUpdate,
  Events.InteractionCreate,
  Events.ShardDisconnect,
  Events.ShardError,
  Events.ShardReady,
  Events.ShardReconnecting,
  Events.ShardResume
]
